openapi: 3.0.0
info:
  title: Vending Machine API
  description: This is an application for tracking various vending machines in Vancouver
  contact:
    email: treziapov@my.bcit.ca
  version: 1.0.0
servers:
- url: /
tags:
- name: vending_machine
  description: Operations available to vending machines
paths:
  /dispenses:
    get:
      tags:
      - vending_machine
      summary: gets dispensed items records
      operationId: app.get_dispense_record
      parameters: 
        - name: start_timestamp
          in: query
          description: Limits the number of records returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits the number of records returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T10:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of dispense events
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/DispenseItem'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string


  /refills:
    get:
      tags:
      - vending_machine
      summary: gets refill items records
      operationId: app.get_refill_record
      parameters: 
        - name: start_timestamp
          in: query
          description: Limits the number of records returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T09:12:33.001Z
        - name: end_timestamp
          in: query
          description: Limits the number of records returned
          schema:
            type: string
            format: date-time
            example: 2016-08-29T10:12:33.001Z
      responses:
        '200':
          description: Successfully returned a list of refill events
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RefillItem'
        '400':
          description: invalid request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

components:
  schemas:
    DispenseItem:
      required:
      - amount_paid
      - payment_method
      - item_id
      - transaction_time
      - vending_machine_id
      - trace_id
      type: object
      properties:
        vending_machine_id:
          type: string
          format: uuid
        amount_paid:
          type: number
          example: 2.5
        payment_method:
          type: string
          example: cash
        transaction_time:
          type: string
          format: date-time
        item_id:
          type: integer
          example: 4033
        trace_id:
          type: string
          format: uuid
    RefillItem:
      required:
      - item_id
      - item_quantity
      - refill_time
      - staff_name
      - vending_machine_id
      - trace_id
      type: object
      properties:
        vending_machine_id:
          type: string
          format: uuid
        staff_name:
          type: string
          example: John Doe
        refill_time:
          type: string
          format: date-time
        item_id:
          type: number
          example: 4012
        item_quantity:
          type: number
          example: 3
        trace_id:
          type: string
          format: uuid
        